== O Estudo do Desenvolvimento Humano

:online: {gitrepo}/blob/master/livro/capitulos/code/{cap}
:local: {code_dir}/{cap}
:img: {img_dir}/{cap}
:dot: {dot_dir}/{cap}

.Objetivos do capítulo
____
Ao final deste capítulo você deverá ser capaz de:

* objetivo 1
* objetivo 2
* objetivo N
____

Abordaremos aqui as noções gerais acerca da Psicologia do 
Desenvolvimento e a contribuição que esse campo do saber oferece 
aos profissionais da educação possibilitando tornar mais eficaz o 
cumprimento do exercício profissional. Compreender os fatores 
múltiplos que influenciam no desenvolvimento e na vida humana é de 
extrema necessidade a todos que lidam com a dimensão humana. Um 
físico, engenheiro, médico, enfermeiro, assistente social 
administrador ou profissional de qualquer outra área relacionada com 
o ser humano enfrentará as repercussões de uma formação 
defeituosa em seu curso de graduação sem a consciência do papel da 
psicologia, quando se trata de oferecer contribuições científicas 
ou técnicas para qualquer área que envolve o homem.

A Psicologia do Desenvolvimento é o estudo sistemático do 
desenvolvimento do ser em todos os aspectos desde a formação, no 
momento da fecundação ou anterior a ela, até o envelhecimento ou 
estágio final da vida. Ela se ocupa da compreensão do comportamento 
humano em que se considera a contínua interação entre fatores 
passados e presentes, entre configurações hereditárias 
integradoras das estruturas e funções neurofisiológicas, 
experiências de aprendizagem e contexto sócio-histórico-cultural 
em que se desenvolve. Assim, essa área de conhecimento da Psicologia 
se constitui numa dimensão charneira entre a genética, a 
neurologia, a sociologia e outros campos do saber, o que a torna com 
alta complexidade e conduz o estudo do desenvolvimento do humano da 
concepção até a morte numa perspectiva interdisciplinar. Dessa 
forma, reconhecemos que mesmo se tratando da mesma espécie, os seres 
humanos diferem em seu patrimônio hereditário e contexto 
sociocultural e assim se constituem pessoas com evidentes diferenças 
individuais e complexidade do comportamento humano.

Compreendemos que o desenvolvimento humano é um processo longo e 
gradual de mudanças em que cada pessoa, ao seu tempo e no seu jeito 
de ser no mundo, dá sentido ao que vive. Assim, o passado, presente 
e futuro constituem demarcações individuais do existir. A vida e 
valores e características de uma pessoa se configuram em um 
determinado contexto histórico. Afinal, além da dimensão 
individual o tempo tem também uma dimensão social.

// TODO: Falta legenda para o gráfico

["graphviz"]
----
include::{dot}/fases-da-vida.dot[]
----

=== Objetivos da Psicologia do Desenvolvimento
____

Consideramos que a Psicologia do Desenvolvimento persegue três 
objetivos em que o primeiro deles volta-se para a identificação da 
gênese dos comportamentos psicomotores, afetivos, cognitivos e 
sociais e seus impactos ao longo da vida. O segundo refere-se ao 
reconhecimento dos fatores, mecanismos e processos responsáveis pelo 
surgimento dos comportamentos e suas mudanças. O terceiro 
corresponde ao estabelecimento de fases ou estágios no 
desenvolvimento, em que se considera como um período de tempo no 
qual o ciclo vital apresenta uma configuração particular de 
características físicas, emocionais sociais e intelectuais.


=== Breve histórico da Psicologia do Desenvolvimento

==== A visão desenvolvimento na Grécia Antiga
  
Ao longo dos séculos tem havido mudanças no interesse pelo estudo 
do desenvolvimento. *Na antiguidade grega, Platão, em sua 
perspectiva filosófica idealista*, postulou que os seres humanos 
não poderiam conhecer a realidade como ela é, visto que duas 
pessoas têm diferentes percepções do mundo real, pois este é 
modificado pelas percepções individuais. Enquanto *Aristóteles 
acreditava que as pessoas compreendiam a realidade a partir de suas 
impressões sensoriais*.


****

[frame="none"]
|====

A educação contra a alienação na Alegoria da Caverna. 

>| Fonte: História das Ideias Pedagógicas de Moacir Gadotti, 2003, 8a ed., p.35
|====
____
*PLATÃO* (427-347 a.C.), principal discípulo de Sócrates e mestre de
Aristóteles, foi um importante filósofo. Nascido em Atenas, de uma
família nobre, este em contato com as personalidades mais importantes
de sua época.

Entre as várias obras que deixou destacam-se _República, Alegoria da
caverna, Banquete, Sofista, Leis_. Através delas, formula a tarefa
centra de toda educação: retirar o ``olho do espírito'' enterrado no
grosseiro pantanal do mundo aparente, em constante mutação, e fazê-la
olhar para a luz do verdadeiro ser, do divino; passar gradativamente
da percepção ilusória dos sentidos para a contemplação da realidade
pura e sem falsidade. Para ele, só com o cumprimento dessa tarefa
existe educação, a única coisa que o homem pode levar para a
eternidade. Para que se alcance esse objetivo é necessário
``converter'' a alma, encarar a educação como ``arte de conversão''.

Em sua utópica república todas as mulheres deveriam ser comuns a todos
os homens. Para ele as autoridades do Estado deveriam decidir quem
geraria filhos, quando, onde e quantas vezes.

Estas e outras teses controversas da obra de Platão não conseguem
obscurecer sua contribuição perene para a concepção do homem
ocidental e da educação.

==== Relação da Alegoria da Caverna com a educação

O mito conta a história de homens que viviam em uma grande fenda no chão, 
onde a luz se projetava da superfície que fazia com que vissem apenas o que 
a sombra projetava. Pensavam então que as coisas da superfície eram a daquela 
forma. Um dia um desses homens que lá vivia, ficou curioso sobre o que seria 
aquilo, mas ninguém sabia, e, então resolveu subir para superfície e além do que via. 

Chegou à entrada da caverna, saiu e olhou admirado para as árvores e 
para os campos que se abriam à sua frente: cores, formas, brilho. Emocionado, 
embora ainda assustado, um maravilhoso pôr do sol, completamente louco, no bom sentido, 
viu surgir na escuridão da noite, escuridão tão sua conhecida, um lindo feixe de luz, 
a luz da lua cheia. Não conseguiu dormir, não quis, queria observar tudo, mesmo no escuro. 
Pôde ver o nascer do sol. Com a nova descoberta não poderia parar, continuaria seguindo o 
feixe de luz até ao seu último grau, antes, resolveu  voltar para a caverna e  
contar aquelas novidades ao seu povo. 
Voltou... Pensando em seus companheiros vivendo fora da escuridão daquela caverna. Estariam 
livres para sempre. Quando chegou junto aos seus companheiros, inicialmente, fizeram festa. 
Quando a empolgação inicial passou e todos estavam prontos para suas vidas rotineiras, ele 
quis contar todas as novidades que vira fora daquele lugar. Quando, no entanto, contou 
o que vira e descobrira, e quis convencer os outros a irem com ele, em direção ao feixe 
de luz, estes se revoltaram o apedrejaram jogando-o na maior fenda conhecida.


Essa alegoria demonstra não apenas a resistência ao novo, mas o quanto os nossos sentidos 
podem nos enganar. Em relação ao acesso ao conhecimento, retrata que esse deve não deve 
ser repassado mecanicamente, deve ser construído sob o aspecto da reflexão, do todo. 
Platão buscava um conhecimento profundo das coisas, a essência do ser e das coisas, 
além do mundo sensível. A educação em função da expressão do seu pensamento, ele queria 
mostrar um mundo totalmente diferente. 

____

****

****

[frame="none"]
|====
>| A virtude está no meio-termo
>| Fonte: História das Ideias Pedagógicas de Moacir Gadotti, 2003, 8a ed., p.35
|====

____

*ARISTÓTELES* (384-322 a.C.) é, com Platão, um dos mais geniais
filósofos gregos e o maior sistematizador de toda a Antiguidade.

Nascido na Macedônia, ingressa com 17 anos na Academia de Atenas, onde
permanece estudando e ensinando durante 20 anos, até a morte de seu
mestre, Platão.

Contrário ao idealismo de seu mestre, Aristóteles prega de maneira
realista que as ideias estão nas coisas, como sua própria essência. É
também realista em sua concepção educacional; expõe três fatores
principais que determinam o desenvolvimento espiritual do homem:
``disposição inata, hábito e ensino''. Com isso, mostra-se favorável a
medidas educacionais ``condicionantes'' e acredit que o homem pode
tornar-se a criatura mais nobre, como pode tornar-se a pior de todas,
que aprendemos fazendo, que nos tomamos justos agindo fustamente.

____

****

Na Idade Média (séculos XI ao XIV) as questões relacionadas aos 
processos relativos ao desenvolvimento humanos foram conduzidas com 
desinteresse. Somente no período da Renascença, a partir de um 
movimento humanitarista os estudos acerca do desenvolvimento do ser 
humano na sociedade começam a ser focalizados. Os estudos de 
Pestalozzi, Rousseau e Tiedemann abrem caminho para o período 
pré-científico no estudo do desenvolvimento infantil. A fase 
pré-científica caracteriza-se pelo uso do método da descrição 
dos comportamentos das crianças sem buscar a origem dos mesmos. 
Assim esses estudos limitaram-se à observação de comportamentos 
específicos, sem a atenção ao controle das técnicas de 
investigação e da interpretação dos resultados dos estudos.

Somente no século XIX as bases para a fase experimental na 
psicologia do desenvolvimento são lançadas por Darwin, Hall e 
outros, com o uso da observação controlada e o método de 
questionário, análise e interpretação estatística. Entre os 
séculos XIX e XX despertou-se para o estudo da infância enquanto 
fase da vida humana que apresenta especificidade. Do século XX para 
este século o interesse pelo estudo da adolescência vem 
acontecendo, bem como se verifica a tendência em analisar a 
evolução para atingir a fase adulta e velhice. 


[quote]
O que aconteceu no século passado com a descoberta da infância, 
voltou a acontecer neste século com a adolescência. Apenas 
recentemente, nas nações e culturas industrializadas, os adultos 
começaram a levar em conta as necessidades e capacidades 
fisiológicas e psicológicas características dos adolescentes, e 
esta percepção deu-lhes a oportunidade de reconhecer um estádio de 
desenvolvimento humano. (<<"SPRINTHALL08","Sprinthall, 2008, p. 7">>)

Enquanto o estudo do desenvolvimento adolescente está sendo 
desvelado, se discute a urgência em priorizar o estudo do 
desenvolvimento do idoso, visto ser essa população a que mais irá 
crescer neste século. E nessa realidade, conhecer características e 
necessidades desse setor populacional é imprescindível para se 
processar a inclusão -- principalmente a escolar/digital -- com 
vistas à constituição de um mundo sócio/economicamente 
sustentável.

== Desenvolvimento: maturação e aprendizagem

Assim como a hereditariedade e o meio ambiente, a maturação e 
aprendizagem são processos interativos do desenvolvimento. Em que a 
maturação corresponde a padrões de diferenciação do 
comportamento que ocorrem por mudanças ordenadas e sequenciais. E 
que a aprendizagem implica em aquisição realizada na interação 
com o meio.  Esses processos se desenvolvem intimamente relacionados. 
Contudo, entre os estudiosos, não há acordo acerca do entendimento 
sobre como ocorre essa relação. Para alguns a maturação antecede 
a aprendizagem, sendo um processo inato. Para outros a maturação 
cria condições para aprendizagem, que, estimula o processo 
maturacional. Para nós, educadores na escola contemporânea, é a 
crença na maturação como processo dinâmico que fundamenta nossa 
ação educativa. Visto que não se espera simplesmente a maturação 
ocorrer para que o ser possa desenvolver a aprendizagem, mas se cria 
condições para que esta ocorra.

== Diferença entre crescimento e desenvolvimento


É importante fazer essa diferenciação para facilitar a 
compreensão de alguns conceitos fundamentais da psicologia do 
desenvolvimento. O crescimento deve ser entendido como referente ao 
aspecto quantitativo das proporções do corpo, tratando do aumento 
físico das proporções do corpo. Enquanto que o desenvolvimento 
refere-se mais ao aspecto qualitativo, sem, contudo excluir alguns 
aspectos quantitativos. 

O crescimento estaciona em determinada idade do ser humano, ao 
atingir a maturidade biológica. Diferentemente do processo de 
desenvolvimento que permanece da concepção até a morte.

Apesar das diferenças que caracterizam o desenvolvimento de cada 
pessoa, há certos princípios universais do desenvolvimento. 
Fundamentados em Moreira (2000), trataremos de alguns princípios 
maturacionais previsíveis de serem observados no desenvolvimento 
humano.

== Princípios gerais do desenvolvimento humano


O desenvolvimento se processa por etapas:: o desenvolvimento humano 
Se dá por fases que apresentam características próprias. Contudo, 
a definição dos critérios de periodização da vida humana não é 
única. Há teóricos que abordam o desenvolvimento sob o aspecto 
físico como Gesell, aspecto cognitivo segundo estudos de Piaget, ou 
ainda pelo aspecto psicossexual segundo as investigações de Freud. 
Mesmo havendo grande diversidade de critérios para o estabelecimento 
de fases no desenvolvimento do ser humano há uma convergência para 
o entendimento de que o desenvolvimento implica em novos padrões de 
comportamentos constituídos por processos de reintegração 
sucessiva de estruturas comportamentais e/ou orgânicas.

O desenvolvimento, embora contínuo e sequencial, é marcado por profundas transformações:: 
A evolução implica em transformações 
estruturais possibilitadores de novos desempenhos. Tanto o 
crescimento como o desenvolvimento produzem mudanças nos componentes 
físico, mental, emocional e social que ocorrem em ordem invariante. 
Uma constatação desse princípio é que a criança antes de correr, 
anda e engatinha.

O desenvolvimento é direcional e se dá numa direção céfalo-caudal e próximo distal:: 
A embriologia corrobora esse 
princípio com a constatação que o organismo desenvolve primeiro a 
cabeça, em seguida o tronco e os membros. Por direção 
próximo-distal diz-se de um desenvolvimento que acontece do centro 
(cérebro/medula espinhal -- eixo central) para a periferia do corpo 
(membros superiores e inferiores). Inicialmente há crescimento e 
desenvolvimento das partes próximas ao cérebro e depois se estende 
descendentemente até as partes mais distantes. 

O desenvolvimento caminha de atividades gerais para as específicas:: 
o comportamento motor se desenvolve de respostas difusas e não 
diferenciadas para as mais específicas e elaboradas. Quando tocamos 
o corpo de um recém-nascido, ele responde com movimentos gerais 
(todo o corpo se move), com o desenvolvimento do organismo, apenas a 
parte do corpo diretamente estimulada responde ao estímulo.

O desenvolvimento se dá em velocidade diferente para diversas partes do corpo:: 
A cabeça cresce intensamente do nascimento até os dois 
anos de idade quando desacelera esse crescimento. O tronco cresce 
significativamente até o um ano e os membros superiores e inferiores 
em torno dos dois anos começam um crescimento acelerado. Em cada 
aspecto o ser apresenta ritmos diferentes nas diversas fases. No 
aspecto cognitivo a capacidade de raciocínio lógico 
indutivo-dedutivo aparece na adolescência.  

.Os fatores que influenciam o desenvolvimento humano...
****
____
<<"BOCK08","Bock, 2008, p. 99">>
____

Vários fatores indissociados e em permanente interação afetam 
todos os aspectos do desenvolvimento. São eles:

Hereditariedade:: a carga genética estabelece o potencial do 
indivíduo, que pode ou não desenvolver-se. Existem pesquisas que 
comprovam os aspectos genéticos da inteligência. No entanto, a 
inteligência pode desenvolver-se aquém ou além do seu potencial, 
dependendo das condições do meio que encontra.

Crescimento orgânico:: refere-se ao aspecto físico. O aumento de 
altura e a estabilização do esqueleto permitem ao indivíduo 
comportamentos e um domínio do mundo que antes não existiam.
+
Pense nas possibilidades de descobertas de uma criança, quando 
começa a engatinhar e depois a andar, em relação a quando esta 
criança estava no berço com alguns dias de vida.

Maturação neurofisiológica:: é o que torna possível determinado 
padrão de comportamento. A alfabetização das crianças, por 
exemplo, depende dessa maturação. Para segurar o lápis e 
manejá-lo como nós, é necessário um desenvolvimento neurológico 
que a criança de 2, 3 anos não tem. Observe como ela segura o 
lápis.

Meio:: o conjunto de influências e estimulações ambientais altera 
os padrões de comportamento do indivíduo. Por exemplo, se a 
estimulação verbal for muito intensa, uma criança de 3 anos pode 
ter um repertório verbal muito maior do que a média das crianças 
de sua idade, mas, ao mesmo tempo, pode não subir e descer com 
facilidade uma escada, porque esta situação pode não ter feito 
parte de sua experiência de vida.

****

=== Análise e reflexão 

Com base nos princípios gerais do desenvolvimento humano, reflita 
sobre eles e tente estabelecer uma relação entre esses princípios 
e a aprendizagem escolar. 

////
Sempre termine os arquivos com uma linha em branco.
////

