== Desenvolvimento humano e aprendizagem: o adolescente e sua relação com as tecnologias.

:cap: cap8
:online: {gitrepo}/blob/master/livro/capitulos/code/{cap}
:local: {code_dir}/{cap}
:img: {img_dir}/{cap}
:dot: {dot_dir}/{cap}

Neste início de século as tecnologias da informação e comunicação 
e em especial, digitais, trazem uma nova perspectiva de linguagem 
que fazem parte do cotidiano dos alunos que transcende os muros 
das escolas. Os estudantes já trazem um pensamento estruturado a 
partir do contato com novas tecnologias. Portanto, utilizá-las 
aproximar-se das novas gerações.

Em capítulo anterior entendemos que as transformações intelectuais,
na adolescência, são de extrema importância, pois é nessa fase 
que a inteligência toma a sua forma final com o pensamento abstrato 
ou formal, segundo Piaget (1949), essa transformação ocorre entre 
os 11-12 anos e os 14-15 anos. A mente do adolescente deixa 
de ser uma mente apenas absorvente e ligada a informações concretas. 
A partir desta fase o ser humano lida com a necessidade de criar, de 
interagir e de transformar. Para (Sprinthall & Collins, 1994), 
o desenvolvimento cognitivo do adolescente não se limite apenas 
a capacidade de desenvolver operações mentais, mas, essa fase 
da vida, contempla-se com novas capacidades de invenção 
de novos problemas e a descoberta de novas questões. Portanto é 
uma fase em que há uma necessidade de “quebra de conceitos”, 
“mudança de valores”, do recriar.

