== DESENVOLVIMENTO COGNITIVO

:cap: cap5
:online: {gitrepo}/blob/master/livro/capitulos/code/{cap}
:local: {code_dir}/{cap}
:img: {img_dir}/{cap}

.Objetivos do capítulo
____
Ao final deste capítulo você deverá ser capaz de:

* objetivo 1
* objetivo 2
* objetivo N
____


O desenvolvimento cognitivo é entendido como o processo pelo qual o ser humano constrói o conhecimento. A sequência contínua e dinâmica de operações que ocorrem na aquisição de conhecimento envolve diversas funções cognitivas como atenção, memória, linguagem, percepção e raciocínio. Essas funções se desenvolvem em interação entre si, visto que o ser humano existe numa totalidade e assim se desenvolve em sua condição de aprender.

Estudos acerca do desenvolvimento cognitivo, sob o olhar de posições teóricas encontradas no universo científico da Psicologia referindo-se a modelos díspares de homem, enfatizam a relação entre pensamento e linguagem. Ambos carregando verdades imprescindíveis a quem anseia conhecer cada vez mais os fenômenos do comportamento humano. 

Estudaremos o aspecto cognitivo do desenvolvimento humano sob visões teóricas diversas com ênfase nas concepções contemporâneas interacionistas, que concebem o conhecimento como construção que se dá na interação entre sujeito e objeto.

Uma das perspectivas teóricas emana do pensamento do filósofo inglês John Lock (1632 - 1704) e cresce com os trabalhos de psicólogos ambientalistas como J B Watson (1878 - 1958), representantes respectivamente da teoria behaviorista e neobehaviorista que dominaram a psicologia entre as décadas de 50 e 80. Na análise behaviorista o indivíduo aprende o sistema linguístico de sua comunidade verbal por mecanismos, pelos quais o indivíduo reage, utilizando a linguagem em relação aos outros e em relação a si mesmo (o pensamento). A ligação entre pensamento e linguagem se apresenta no behaviorismo radical de Skinner com a crença que nega a existência de eventos privados, embora questione a sua suposta natureza física e seu status enquanto categoria explicativa do comportamento, defendendo que o pensamento é apenas comportamento, verbal ou não, encoberto ou aberto.

Os comportamentalistas ao se referirem à linguagem como comportamento verbal afirmam que as palavras são respostas aprendidas por associação e reforçamento. A relação entre a palavra e seu significado existe enquanto percepção simultânea de determinado objeto. Há uma associação palavra -- objeto, que pode fortalecer-se, enfraquecer ou ser extinta em função das contingências reforçadoras. A linguagem surge como mecanismo social que medeia a passagem do comportamento público para o privado em que as palavras sofrem mudanças externas e quantitativas, bem como são capazes de produzir mudanças no ambiente. Nessa concepção o organismo é visto como ser que reage ao ambiente modificando-se, e como ser que opera sobre seu ambiente, modificando-o.

Outro paradigma existente no campo epistemológico da psicologia surge a partir do pensamento inatista. Dentre os psicólogos que enfatizam tais ideias estão Carl Rogers e o psicolinguista Noam Chomsky. Este defende que o sistema nervoso humano contém mecanismos inatos possibilitadores da criança construir regras de linguagem. Nessa visão, as crianças adquirem a linguagem de uma maneira maturacional, biologicamente determinada tal como elas aprendem a andar. Assim, a linguagem é um processo que se desenvolve de dentro para fora.

A luta entre as concepções materialistas e idealista na psicologia tem sido mais acirrada que em qualquer outra ciência. A dualidade predominante reflete-se na incompatibilidade entre essas estruturas teóricas, com seus tons metafísicos e idealistas e bases empíricas sobre as quais se edificaram.

=== DESENVOLVIMENTO COGNITIVO NA PERSPECTIVA INTERACIONISTA DE PIAGET E IMPLICAÇÕES PEDAGÓGICAS

Jean Piaget, cientista suíço de expressiva agudeza intelectual, desenvolveu investigações sobre o desenvolvimento do pensamento que o constituiu destaque dentre os estudiosos do desenvolvimento cognitivo. Suas ousadas proposições acerca do desenvolvimento cognitivo ofereceram contribuições fundamentais para que no mundo contemporâneo se tenha a compreensão que temos acerca de como se desenvolve a cognição. Suas investigações sobre o desenvolvimento do pensamento oportunizaram entender como se dá o processo de desenvolvimento cognitivo do nascimento até a adolescência. Para esse pesquisador a inteligência é uma estrutura que tem a função de ajustar o organismo às realidades do meio. Em que meio tem o sentido de meio do conhecimento e refere-se a tudo que está disponível para o indivíduo enquanto desafio a sua inteligência. O conceito piagetiano de meio não corresponde a um sentido genérico relativo a meio ambiente. Piaget foi um dos primeiros estudiosos a colocar o conhecimento como não predeterminado nas estruturas internas do indivíduo ou como preexistentes nos objetos e sim como uma construção resultante de trocas dialéticas realizadas entre o indivíduo e o meio do conhecimento. O termo construtivismo é característico da proposição teórica de Piaget e foi por ele usado, pela primeira vez, na década de setenta. Essa expressão refere-se aos mecanismos subjacentes à construção das estruturas cognitivas.
Nessa perspectiva, a inteligência é uma estrutura biológica, e assim como as outras, tem a função de realizar adaptações do organismo. As adaptações intelectivas se fazem por meio de dois processos complementares que os nomeou de assimilação e acomodação. Por assimilação entende-se o processo de incorporação dos desafios e informações do meio aos esquemas mentais já existentes. Enquanto acomodação corresponde ao processo de criação ou mudança de esquemas mentais para que ocorra a assimilação. Na linguagem piagetiana esquema significa a condição inicial das trocas que se efetuam entre o indivíduo e o meio. No humano os esquemas iniciais, ponto de partida da interação sujeito meio, são os reflexos. A partir deles todos os demais esquemas são produzidos por assimilação e acomodação.
==== Relação pensamento linguagem na perspectiva de Piaget
Piaget tenta escapar dessa dualidade inevitável levantando a questão da interrelação objetiva de todos os traços característicos do pensamento infantil por ele observados. Sua concepção do desenvolvimento do pensamento baseia-se na premissa, extraída da psicanálise, de que o pensamento infantil é original e naturalmente autístico, se transformando em pensamento realista sob longa e persistente pressão social. O autismo é, aqui considerado, a forma original e mais primitiva do pensamento. A lógica aparece relativamente mais tarde e o pensamento egocêntrico é o elo entre ambos.
A base da crença de Piaget é fornecida pelas pesquisas que realizou sobre o uso da linguagem pelas crianças. Suas observações sistemáticas levaram-no à conclusão de que todas as conversas infantis podem ser divididas e classificadas em dois grupos: egocêntrica e socializada. Na linguagem egocêntrica a criança fala apenas para si própria, sem interesse pelo seu interlocutor, não tenta comunicar-se, não espera resposta e, frequentemente, sequer se preocupa em saber se alguém a ouve. Na linguagem socializada ela tenta estabelecer uma espécie de comunicação com outros. Pede, ordena, ameaça, transmite informações e faz perguntas.
Nessa perspectiva teórica a linguagem segue o desenvolvimento do pensamento até tornar-se parte dele, as formas como as palavras são usadas e os significados atribuídos a elas refletem os níveis de desenvolvimento cognitivo, o que permite considera-la como um mapa do pensamento.
Para Piaget o processo da linguagem não traz em si um correspondente progresso em operações, ao passo que o inverso é uma realidade. Nessa afirmação pode-se verificar uma posição filosófica, apesar dele tentar evitar teorizações, sua obra acaba extrapolando os limites da ciência factual pura. A própria recusa deliberada da filosofia já é, em si mesma, uma filosofia -- e uma filosofia que pode envolver o seu proponente em muitas contradições.
A teoria piagetiana defende que durante os dois primeiros anos de vida a linguagem tem um papel insignificante no desenvolvimento da criança. Tendo em vista que sua forma de agir sobre o mundo e de compreendê-lo são individuais e construídas no plano de ação imediata. A criança se relaciona com o mundo e o elabora por meio dos seus sentidos e movimentos (período sensório motor).
Da inteligência sensório-motora surge a função simbólica, possibilidade de representação, que cria condições para aquisição e desenvolvimento da linguagem. Nessa concepção a linguagem integra-se à função simbólica. Ela não é sua causa e sim seu resultado. Mais ainda, ela é apenas um caso particular das formas de simbolização. E como tal diz respeito aos sistemas de signos coletivos que transmitem ao indivíduo uma porção de conceitos, um sistema pronto de classificações e de relações que vão sendo aprendidos e elaborados por ele de acordo com seus esquemas de ação e de pensamento.
Somente o desenvolvimento do pensamento operatório possibilita ao indivíduo aprender as relações lógicas, de abstração e de generalização. A partir desse estágio o conhecimento se constrói sobre proposições e hipóteses enunciadas verbalmente. A palavra torna-se uma condição necessária, embora não suficiente, do conhecimento lógico-abstrato.
As uniformidades de desenvolvimento estabelecidas por Piaget aplicam-se ao meio dado, nas condições em que o pesquisador realizou seu estudo. Não são leis da natureza, mas leis históricas e socialmente determinadas. A propósito, Piaget recebeu várias críticas por não ter dado a devida importância à situação social e ao meio. O fato de a fala ser mais egocêntrica ou mais social depende não só da idade da criança, mas das condições que a cercam. Num meio social em que as crianças têm mais atividades em grupo que as crianças observadas por Piaget em uma escola de Genebra, o coeficiente de egocentrismo apresenta-se um tanto menor.
Para essa proposição teórica a inteligência relaciona-se com a adaptação do homem ao mundo externo e se desenvolve progressivamente como resultado da equilibração majorante de estruturas que se constituem durante o processo de desenvolvimento. Para Piaget esse fator é o mais fundamental na estruturação da Inteligência. Para compreender o termo piagetiano ``equilibração majorante'' devemos entender que se refere ao processo de desenvolvimento intelectual ocorrido numa estrutura cognitiva que tende a funcionar em equilíbrio, aumentando o grau de organização interna e de adaptação ao meio. Quando esse equilíbrio é comprometido por experiências não assimiláveis, o organismo (mente) se reestrutura (processo de acomodação) para construir novos esquemas de assimilação restabelecendo o equilíbrio, chamado por Piaget de equilibração majorante e considerado fator preponderante no desenvolvimento mental cognitivo. Tal fator possibilita aumento de conhecimento (aprendizagem). Nessa perspectiva aprender é um mecanismo desenvolvido a partir da capacidade de reequilibração. E o ensino precisa ativar esse mecanismo.
Para percebermos as implicações pedagógicas da abordagem construtivista na educação em que a escola tem papel relevante na construção da inteligência trazemos as ideias desenvolvidas por Piaget a partir de estudo/observação no comportamento infantil e adolescente e que representam fundamentos para alcançarmos também a compreensão do comportamento intelectivo adulto e idoso. Para ele: 
[quote]
A criança (sujeito) constitui com o meio (objeto) uma totalidade. À medida que esse meio se modifica, no caso quando a escola entre em cena na vida da criança, novas estimulações passam a exigir-lhe novas condutas, tirando-a do estado de equilíbrio cognitivo a que estava acostumada. O resultado das novas solicitações feitas, pelo ambiente escolar, à criança, deve ser o de leva-la a formar novos padrões de conduta ou esquemas, aumentando e tornando mais complexo o seu repertório de condutas cognitivas. Assim, o processo de ensino aprendizagem deve ser de propiciar à criança o aparecimento de várias capacidades especiais que lhe assegurem o desenvolvimento cognitivo. Através de cada uma das disciplinas que compõem o currículo do aluno, isto será possível, dependendo da forma como seja conduzido o processo pedagógico. (Coutinho, 1999, p. 122)

Assim, ser professor de qualquer disciplina implica em ser um profissional detentor de boa formação pedagógica afinal:
[quote]
[...] o ensino em nossas escolas não deve se limitar apenas a transmitir ao aluno determinados conhecimentos ou a formar certo número de aptidões, de hábitos. Uma de suas tarefas primordiais deve ser, sem dúvida, desenvolver o pensamento do aluno, a sua capacidade de analisar e generalizar fenômenos da realidade, de raciocinar corretamente; numa palavra, desenvolver ``no todo'' as suas estruturas operatórias. No plano cognitivo o desenvolvimento do pensamento lógico deve ser, portanto, uma das principais tarefas da escola. (Ibidem, p. 124)

 	Em nosso fazer pedagógico, para atingirmos as capacidades do pensamento lógico de nossos aprendentes, é imperativo nos instrumentalizar de conhecimentos esclarecedores acerca de como as possibilidades do pensamento lógico se desenvolvem. Para tanto é imprescindível nos apropriarmos da noção de estágio proposta por Piaget, noção central na abordagem piagetiana sobre o desenvolvimento cognitivo. Para ele os estágios são estruturas de conjunto em que cada estrutura se relaciona ao todo e somente tem significado nesse todo. Possuem caráter integrativo, sendo as estruturas de um nível integradas no nível subsequente. E têm um nível de preparação -- esquemas construídos no estágio anterior -- e um nível de acabamento -- construção de novos esquemas. Por fim, os estágios apresentam uma ordem de sucessão invariável em uma cronologia variável. Assim, na sequência dos estágios podem ocorrer defasagens.
____
Em sua proposição teórica Piaget apresenta três grandes estágios de desenvolvimento cognitivo, cada um com subestágios. O primeiro deles é o estágio da inteligência sensório-motora que consiste em adaptação prática ao mundo. Formada, progressivamente, após o nascimento, a partir dos reflexos -- esquemas mais primitivos de assimilação -- e desenvolvida em seis estágios por meio dos quais a criança realiza adaptações inteligentes. O segundo é o estágio da inteligência operatório-concreto, dividido em dois subestágios: Pré-operatório e Lógico-concreto. O pré-operatório é um período de preparação para as operações lógico-concretas vivenciado dos dois aos sete anos. Nesse subestágio verifica-se o desenvolvimento da linguagem impactante na socialização da ação, marcada pela interação entre indivíduos, no desenvolvimento do pensamento por meio do pensamento verbal (finalismo -- porquês, animismo e artificialismo) e no desenvolvimento da intuição. O subestágio lógico-concreto, vivenciado dos sete aos 12 anos, é marcado pelo surgimento do pensamento lógico sobre as coisas concretas compreendendo as relações entre coisas e capacidades para classificar objetos, superação do egocentrismo da linguagem, aparecimento das noções de conservação de substância, peso e volume.

Enfatizamos que as idades acima colocadas servem para dar noção de aproximação cronológica. Como já vimos, a cronologia no desenvolvimento é variável. O terceiro é o estágio da inteligência formal em que se verifica o desenvolvimento de estruturas operatórias formais, marcada pelo pensamento capaz de construir sistemas e teorias abstratas, formando e entendendo conceitos abstratos. Jean Piaget, nascido na Suíça em 1896, foi um Biólogo por formação e estudou Filosofia e Ciências Naturais. Construiu a "Teoria do conhecimento" que serve até hoje como orientação sobre práticas pedagógicas para o professor. Para o autor, a criança se desenvolve a partir das relações que têm com o meio em que vive e desenvolvimento passa por estágios que devem ser classificados para o trabalho do professor em fornecer ferramentas para que o aluno construa seu saber. Para Piaget, o conhecimento é construído na experiência, sendo essa experiência tal como seu valor moral e cultural. Outra máxima de Piaget é sobre a relação do professor com o aluno, que deve se fazer de maneira mútua e não unilateral, democratizando-as.

Fonte: PELLEGRINI, Denise. "Aprenda com eles e ensine melhor" Revista Nova Escola. Janeiro/Fevereiro de 2001.

JUVENTUDE: PROJETO DE VIDA

Conforme Piaget, a personalidade começa a se formar no final da infância, entre 8 e 12 anos, com a organização autônoma das regras, dos valores, a afirmação da vontade. Esses aspectos subordinam-se num sistema único e pessoal e vão-se exteriorizar na construção de um projeto de vida. Esse projeto é que vai nortear o indivíduo em sua adaptação ativa à realidade, que ocorre através de sua inserção no mundo do trabalho ou na preparação para ele, quando ocorre um equilíbrio entre o real e os ideais do indivíduo, [pg. 106] isto é, de revolucionário no plano das ideias, ele se torna transformador, no plano da ação.

É importante lembrar que na nossa cultura, em determinadas classes sociais que ``protegem'' a infância e a juventude, a prorrogação do período da adolescência é cada vez maior, caracterizando-se por uma dependência em relação aos pais e uma postergação do período em que o indivíduo vai se tornar socialmente produtivo e, portanto, entrará na idade adulta.

Na idade adulta não surge nenhuma nova estrutura mental, e o indivíduo caminha então para um aumento gradual do desenvolvimento cognitivo, em profundidade, e uma maior compreensão dos problemas e das realidades significativas que o atingem. Isto influencia os conteúdos afetivo-emocionais e sua forma de estar no mundo.
(BOCK, 2008, p. 139)
____
=== DESENVOLVIMENTO NA PERSPECTIVA INTERACIONISTA DE VYGOTSKY E IMPLICAÇÕES PEDAGÓGICAS
	
Lev Vygotsky em parceria com seus colaboradores Alexander Romanovich Luria (1902-1977) e Alexei Nikolaievich Leontiev (1904-1979) compõe o grupo de teóricos da chamada Psicologia Soviética, que muito se destacou após a revolução de 1917 ao buscar abordar a natureza e significação dos fenômenos psicológicos humanos sob novas bases, perspectivando a democratização do saber produzido pela e para a sociedade do novo contexto político soviético.
Vygotsky buscou uma abordagem possibilitadora de descrição e explicação das funções psicológicas superiores em termos aceitáveis para as ciências naturais. O grande avanço de sua abordagem foi tratar as funções psicológicas a partir do estudo de fenômenos propriamente humanos, sem reduzi-las a inferências extraídas da psicologia animal. Assim, as atividades humanas ganham novo status epistemológico em que a função linguagem ocupa lugar de destaque no desenvolvimento humano pela importância que tem na construção dos processos do pensamento. Com essa posição teórica inaugura-se nova perspectiva para a Psicologia. Esse teórico foi o primeiro psicólogo a visualizar a cultura como integrante da natureza humana, mecanismo por ele chamado de processo de internalização que acontece do interpsíquico para o intrapsíquico. No campo da Psicologia Vygotsky propôs uma abordagem dialética dos fenômenos psicológicos e buscou revelar a gênese social da consciência. Para ele as funções psicológicas são efeito e causa da atividade social do homem. Pois a consciência se constrói no processo de produção social do homem.
A prática profissional como professor de educação especial, psicólogo e a reflexão sobre essas experiências o levou a uma concepção avançada sobre o papel da aprendizagem no desenvolvimento, ampliando os pressupostos acerca da inteligência infantil. Evidencia que na avaliação da capacidade intelectual da criança o desempenho nos testes psicológicos é insuficiente por mensurarem apenas o nível de desenvolvimento cognitivo alcançado, nada informando acerca do desenvolvimento iniciado e ``não atingido ainda'' e com ajuda podem alcançar -- desenvolvimento proximal. Diante disso o papel da escola é ensinar a aprender, permitir que o sujeito trabalhe além do nível de desenvolvimento real (desenvolvimento já completado) mobilizando a zona de desenvolvimento (espaço entre o real e o potencial -- o que está próximo de ser atingido, mas precisa de ajuda para alcançar).
	Na visão de Vygotsky os processos de desenvolvimento e aprendizagem não coincidem. Opondo-se às ideias ate então colocadas, ele fundamenta a posição teórica em que os processos de desenvolvimento podem ser beneficiados pelas aprendizagens. Ou seja, o indivíduo se desenvolve enquanto aprende. Nesse ponto Vygotsky e Piaget se contrapõem. Enquanto o primeiro defende que a aprendizagem antecede o desenvolvimento, o segundo defende que o desenvolvimento antecede a aprendizagem.
==== Relação pensamento linguagem na perspectiva de Vygotsky
O enfoque de Vygotsky sobre a relação linguagem e pensamento dá-se no sentido de buscar compreender as implicações da linguagem no processo de hominização, isto é, na passagem da consciência predominantemente biológica, instintiva, para a racional, em que a palavra não é analisada como uma das funções simbólicas, mas como o sistema simbólico básico, produzido a partir da necessidade de intercâmbio entre os indivíduos durante o trabalho, atividade especificamente humana, que exige a troca de informações e ações conjuntas sobre o mundo.
Nessa perspectiva a linguagem é um produto histórico e significante da atividade mental, que encerra em si o saber, os valores, as normas de conduta, as experiências organizadas pelos antepassados, por isso participa diretamente no processo de formação do psiquismo desde o nascimento. Inicialmente o bebê interage com o meio orientado por motivos biológicos. Suas atividades são impulsionadas por uma consciência reflexológica, pré-consciente. Nesse momento, a linguagem e consciência são duas linhas de ação inteiramente independentes, de um lado tem-se a linguagem pré-intelectual, movida por sensações, uma comunicação expressa, principalmente, pelo choro e através de movimentos, ainda desprovidos de sentido para quem escuta. De outro lado, observa-se uma consciência pré-linguística que não intui, não simboliza. Uma ``inteligência prática'' como denomina Vygotsky, logo, não há pensamento.
O encontro entre a linguagem social -- aprendida no meio -- e a consciência reflexológica é o momento de maior impacto no curso da constituição do pensamento. As imagens e as representações conceituais invadem a inteligência prática, tornando-a consciente. Quando isso acontece não há mais distinção entre linguagem e pensamento, estes passam a ser processos interdependentes, compondo uma única unidade. 
A linguagem intervém na formação e no funcionamento de todos os processos psíquicos. Mas, é em relação ao pensamento que suas implicações são fundamentais e decisivas. Ela está intimamente ligada ao pensamento. Não é nem anterior nem posterior a este, ambos se elaboram juntos no trabalho e por meio dele -- motivo pelo qual a mesma só reflete o que é produzido no contexto das relações sociais. Linguagem e pensamento coexistem numa cumplicidade indissolúvel na qual a primeira dá forma e objetiva a existência do segundo.
=== Lev Vigotsky/Imagem Revista Escola
imagem do cabinha


Lev Vigotsky, nascido em 1896, foi um pensador Bielo-Russo formado em Direito.
Trabalhou com o conceito de que o indivíduo não é cópia do meio no qual vive. Isto é, ele sofre influências de várias direções. Com esse pensamento, Vygotsky se posicionou contra as principais correntes de sua época (pensamento inatista). Para o pensador, o indivíduo sofre influências baseadas em suas experiências que constroem sua vivência, sendo muito importante o grupo cultural no qual esta inserido. O papel do professor nesse desenvolvimento é de ``tradutor'' do conhecimento que o aluno possui de maneira superficial, o professor deve estar entre a zona de "desenvolvimento real" e o "desenvolvimento potencial" na educação. O desenvolvimento real seria a zona de conhecimento que o indivíduo já conhece e o desenvolvimento potencial o que ele poderá conhecer.

Fonte: PELLEGRINI, Denise. "Aprenda com eles e ensine melhor" Revista Nova Escola. Janeiro/Fevereiro de 2001.

==== PENSAMENTO E PALAVRA

O significado de uma palavra representa um amálgama tão estreito do pensamento e da linguagem, que fica difícil dizer se se trata de um fenômeno da fala ou de um fenômeno do pensamento. Uma palavra sem significado é um som vazio; o significado, portanto, é um critério da ``palavra'', seu componente indispensável. Pareceria, então, que o significado poderia ser visto como um fenômeno da fala. Mas, do ponto de vista da Psicologia, o significado de cada palavra é uma generalização ou um conceito. E como as generalizações e os conceitos são inegavelmente atos de pensamento, podemos considerar o significado como um fenômeno do pensamento. Daí não decorre, entretanto, que o significado pertença formalmente a duas esferas diferentes da vida psíquica. O significado das palavras é um fenômeno de pensamento apenas à medida que o pensamento ganha corpo por meio da fala, e só é um fenômeno da fala à medida que esta é ligada ao pensamento, sendo iluminada por ele. 

É um fenômeno do pensamento verbal, ou da fala significativa — uma união da palavra e do pensamento.

Nossas investigações experimentais confirmam plenamente essa tese básica. Não só provaram que o estudo concreto do desenvolvimento do pensamento verbal é possível usando-se o significado das palavras como unidade analítica, mas também levaram a outra tese, que consideramos o resultado mais importante de nosso estudo, e que decorre diretamente da primeira: o significado das palavras evolui. A compreensão desse fato deve substituir o postulado da imutabilidade do significado das palavras.

Do ponto de vista das antigas escolas de Psicologia, o elo entre a palavra e o significado é associativo, estabelecido pela reiterada percepção simultânea de um determinado som e de um determinado objeto. Em nossa mente, uma palavra evoca o seu conteúdo do mesmo modo que o casaco de um amigo nos faz lembrar desse amigo, ou uma casa, de seus habitantes. A associação entre a palavra e o significado pode tornar-se mais forte ou mais fraca, enriquecer-se pela ligação com outros objetos de um tipo semelhante, expandir-se por um campo mais vasto ou tornar-se mais limitada, isto é, pode passar por alterações quantitativas e externas, mas não pode alterar a sua natureza psicológica. Para isso, teria que deixar de ser uma associação. 

Desse ponto de vista, qualquer desenvolvimento do significado das palavras é inexplicável e impossível — uma conclusão que constitui um obstáculo tanto para a Lingüística quanto para a Psicologia. Uma vez comprometida com a teoria da associação, a semântica persistiu em tratar o significado das palavras como uma associação entre o som da palavra e o seu conteúdo. Todas as palavras, das mais concretas às mais abstratas, pareciam ser formadas do mesmo modo em termos do seu significado, não contendo nada de peculiar à fala como tal; uma palavra fazia-nos pensar em seu significado da mesma maneira que qualquer objeto nos faz lembrar de um outro. Pouco surpreende que a semântica sequer tenha colocado a questão mais ampla do desenvolvimento do significado das palavras. O desenvolvimento foi reduzido às mudanças nas conexões associativas entre palavras e objetos isolados: uma palavra podia, a princípio, denotar um objeto e, em seguida, associar-se a outro, do mesmo modo que um casaco, tendo mudado de dono, nos faria lembrar primeiro de uma pessoa e, depois, de outra. A linguística não percebeu que, na evolução histórica da linguagem, a própria estrutura do significado e a sua natureza psicológica também mudam. A partir das generalizações primitivas, o pensamento verbal eleva-se ao nível dos conceitos mais abstratos. Não é simplesmente o conteúdo de uma palavra que se altera, mas o modo pelo qual a realidade é generalizada e refletida em uma palavra.
(VYGOTSKY, 1993)

Após estudarmos o desenvolvimento cognitivo a partir das contribuições de Piaget e Vygotsky podemos compreender quão importante é aprofundarmos estudos possibilitadores do conhecimento acerca de como se desenvolve a inteligência humana e quanto a educação pode oportunizar às pessoas um desenvolvimento que propicie o empoderamento que todos necessitam para termos uma sociedade inclusiva, em que todos sejam educados/escolarizados numa perspectiva de equidade.

=== REFERÊNCIA

COUTINHO, Maria Tereza da Cunha & MOREIRA, Mércia. Psicologia da Educação: um estudo dos processos psicológicos de desenvolvimento e aprendizagem humanos, voltado para a educação. Belo Horizonte: Editora lê, 2000.


SUGESTÕES PARA LEITURA E REFLEXÃO:
http://www.nutes.ufrj.br/abrapec/viiienpec/resumos/R1092-2.pdf 



////
Sempre termine os arquivos com uma linha em branco.
////


